name: Build ETISS and run smoke tests

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build_etiss:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        path: etiss

    - name: ls
      run: |
        pwd
        ls

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-program-options-dev\
          llvm-11-dev libclang-11-dev clang-11
          ninja-build

    - name: CMake config
      run: |
        cmake -B etiss_build -S etiss_source -DCMAKE_INSTALL_PREFIX=etiss_install -G ninja

    - name: CMake build
      run: |
        cmake --build etiss_build --config $BUILD_TYPE --parallel